"""Ticket Management Efficiency

Revision ID: 9be6ddb6876e
Revises: ad85bde556a5
Create Date: 2025-03-12 23:56:59.236447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9be6ddb6876e'
down_revision: Union[str, None] = 'ad85bde556a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revoked_tokens_token', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('refresh_tokens')
    op.drop_constraint('attachments_ticket_id_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comments_ticket_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ticket_history_ticket_id_fkey', 'ticket_history', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_history', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_history', type_='foreignkey')
    op.create_foreign_key('ticket_history_ticket_id_fkey', 'ticket_history', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ticket_id_fkey', 'comments', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_ticket_id_fkey', 'attachments', 'tickets', ['ticket_id'], ['id'])
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='refresh_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey')
    )
    op.create_table('revoked_tokens',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('token', name='revoked_tokens_pkey')
    )
    op.create_index('ix_revoked_tokens_token', 'revoked_tokens', ['token'], unique=False)
    # ### end Alembic commands ###
