"""Added Created by field to the tickets

Revision ID: adca0597b1bf
Revises: 9be6ddb6876e
Create Date: 2025-03-13 15:51:40.121983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adca0597b1bf'
down_revision: Union[str, None] = '9be6ddb6876e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'created_by')
    # ### end Alembic commands ###
